## Gallardo Larez Pablo 

TC Clasificación de números 

23-03-2022

In [1]:
from sklearn.datasets import load_digits

In [2]:
#Observar el dataset
data = load_digits()
data

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [3]:
#Separar la información de nuestro dataset en train y test
from sklearn.model_selection import train_test_split

X = data.data
Y = data.target

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=20)

In [6]:
X_train

array([[ 0.,  0.,  2., ...,  6.,  0.,  0.],
       [ 0.,  0.,  4., ..., 12.,  5.,  0.],
       [ 0.,  0.,  4., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0., 15., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 15., 10.,  0.],
       [ 0.,  0.,  8., ..., 15.,  1.,  0.]])

In [7]:
X_test

array([[ 0.,  0.,  2., ...,  4.,  0.,  0.],
       [ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  6., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  3., ..., 14.,  0.,  0.],
       [ 0.,  0.,  4., ...,  2.,  0.,  0.],
       [ 0.,  0.,  2., ...,  5.,  0.,  0.]])

In [8]:
Y_train

array([0, 8, 8, ..., 5, 6, 9])

In [9]:
Y_test

array([0, 7, 9, 5, 8, 1, 3, 3, 7, 0, 9, 4, 7, 4, 0, 1, 1, 8, 1, 3, 7, 8,
       4, 6, 1, 0, 1, 0, 5, 4, 7, 1, 6, 7, 8, 4, 3, 7, 4, 0, 5, 9, 0, 4,
       8, 7, 4, 3, 6, 3, 9, 2, 2, 5, 7, 3, 7, 8, 3, 8, 6, 6, 8, 6, 8, 5,
       0, 5, 3, 5, 0, 7, 3, 2, 9, 9, 3, 0, 2, 5, 5, 9, 2, 4, 5, 9, 7, 7,
       2, 3, 0, 4, 6, 1, 9, 7, 1, 9, 9, 3, 4, 6, 7, 8, 1, 8, 4, 0, 1, 3,
       6, 5, 5, 5, 1, 6, 0, 6, 2, 8, 9, 4, 1, 3, 4, 0, 6, 7, 7, 9, 8, 7,
       8, 2, 4, 2, 5, 2, 3, 8, 8, 9, 8, 0, 0, 6, 2, 6, 9, 0, 9, 0, 0, 8,
       7, 5, 3, 4, 0, 5, 6, 2, 6, 0, 4, 8, 7, 9, 2, 4, 3, 6, 4, 4, 5, 2,
       8, 0, 7, 7, 3, 2, 2, 9, 0, 7, 2, 1, 6, 7, 9, 1, 5, 1, 6, 4, 6, 1,
       3, 6, 1, 0, 8, 6, 5, 8, 8, 9, 1, 5, 1, 2, 6, 7, 5, 0, 1, 2, 4, 7,
       0, 9, 6, 4, 7, 6, 5, 1, 2, 5, 5, 4, 6, 1, 7, 6, 1, 8, 9, 6, 2, 8,
       5, 8, 3, 3, 9, 0, 3, 7, 9, 9, 1, 7, 0, 0, 5, 7, 3, 6, 3, 8, 6, 3,
       6, 9, 8, 3, 3, 4, 4, 0, 7, 1, 5, 6, 1, 4, 6, 4, 5, 6, 3, 7, 4, 5,
       2, 5, 6, 4, 0, 4, 2, 2, 3, 3, 2, 9, 0, 9, 7,

In [10]:
#Seleccionamos el algoritmo de clasificación a utilizar
from sklearn import svm
from sklearn.svm import SVC

In [11]:
#Creamos nuestro clasificador (o algoritmo de agrupamiento)
clasificador = SVC(kernel='linear', C=0.025)

In [12]:
#Comienza el entrenamiento del modelo
clasificador.fit(X_train, Y_train)

SVC(C=0.025, kernel='linear')

In [13]:
#Prueba el modelo generado
print('SVC', clasificador.score(X_test, Y_test))

SVC 0.975


In [14]:
#Knn
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [15]:
knn= KNeighborsClassifier(n_neighbors =3, metric='minkowski', p=2)
knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3)

In [16]:
#Prueba el modelo generado
print('Knn', knn.score(X_test, Y_test))

Knn 0.9833333333333333


In [17]:
#Arbol de decisión
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(criterion ="entropy", max_depth=3)
tree.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [18]:
#Prueba del modelo generado
print('Tree',tree.score(X_test,Y_test))

Tree 0.5416666666666666


In [19]:
#Naive bayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, Y_train)

GaussianNB()

In [20]:
#Prueba del modelo generado
print('Naive Bayes',gnb.score(X_test,Y_test))

Naive Bayes 0.8861111111111111


SVM            97.5%

KNN o NB       98.33%

DT             54.16%

Naive Bayes    88.61%